name: Deploy

on:
  push:
    branches:
      - master
jobs:
  deploy:
    name: deploy to staging
    runs-on: ubuntu-18.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: test
        run: npm run test
      - name: deploy to staging
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd /whale-wave/ww-message-push-service
            git pull
            npm install
            npm run build
            pm2 restart ww-message-push-service
